[package]
name = "ehframe-bpf-compiler"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
gimli = "0.23.0"
memmap = "0.7.0"
object = "0.23.0"
typed-arena = "2.0.1"
